version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 10
    ignore:
      - dependency-name: "bdk_wallet"
        versions: ["> 2.4.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 10
