bitcoin:
  network: regtest
  url: http://127.0.0.1:18443
  username: foo
  password: rpcpassword
  wallet: test_wallet

key_manager:
  network: regtest
  
key_storage:
  password: secret_password_1
  path: /tmp/regtest/wallet/keys.db

storage:
  path: /tmp/regtest/wallet/storage.db

wallet:
  funding_key: cVt4o7BGAig1UXywgGSmARhxMdzP5qvQsxKkSsc1XEkw3tDTQFpy
  #optional db_path: /tmp/regtest/wallet/wallet.db
