bitcoin:
  network: testnet
  url: "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet

key_storage:
  password: SeCrEt_p4ssw0rd_123!
  path: db/testnet/wallet/keys.db

storage:
  # Stores wallet metadata used by WalletManager (names, pubkeys, indexes).
  path: db/testnet/wallet/storage.db

wallet:
  # Base path for BDK wallet database files
  db_path: db/testnet/wallet/wallet.db
  start_height: 4734673